services:
  # Backend Service
  - type: web
    name: rent-ai-backend
    runtime: node
    plan: free
    region: ohio
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: MONGODB_URI
        sync: false # Isse ye dashboard par value maangega
      - key: NODE_ENV
        value: production

  # Frontend Service
  - type: static
    name: rent-ai-frontend
    runtime: static
    plan: free
    buildCommand: cd frontend/my-project && npm install && npm run build
    publishPath: frontend/my-project/dist